# Generated by Django 5.0.5 on 2025-03-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0002_remove_course_rating_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('Web', 'Web Development'), ('Data', 'Data Science'), ('Business', 'Business & Management'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
