# Generated by Django 5.0.5 on 2025-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_topics',
            field=models.JSONField(default=list),
        ),
    ]
