# Generated by Django 5.0.5 on 2025-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0005_enrollment_completed_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Data Science', 'Data Science'), ('Design', 'Design')], default='Programming', max_length=20),
        ),
    ]
