# Generated by Django 5.0.5 on 2025-03-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
