# Generated by Django 5.0.5 on 2025-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0007_alter_interaction_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.JSONField(default=list),
        ),
    ]
