# Generated by Django 5.0.5 on 2025-03-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorly', '0008_course_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
